const DATA_KEY='assessorPlusTutorRegisterV2';
const state=loadState();
let currentLearnerId=null,currentClassId=null,currentRegisterId=null;
const $=id=>document.getElementById(id);
const pages=[...document.querySelectorAll('.page')];
const nav=[...document.querySelectorAll('[data-nav]')];

function loadState(){try{const saved=JSON.parse(localStorage.getItem(DATA_KEY));if(saved)return normalise(saved)}catch{}return{learners:[],classes:[],registers:[]}}
function normalise(data){return{learners:Array.isArray(data.learners)?data.learners:[],classes:Array.isArray(data.classes)?data.classes:[],registers:Array.isArray(data.registers)?data.registers:[]}}
function save(){localStorage.setItem(DATA_KEY,JSON.stringify(state));renderHome()}
function uid(prefix){return`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function dateText(v){return v?new Date(`${v}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function minsText(mins){const sign=mins<0?'-':'';mins=Math.abs(Math.round(mins));return`${sign}${Math.floor(mins/60)}h ${mins%60}m`}
function timeToMins(t){if(!t)return 0;const[h,m]=t.split(':').map(Number);return h*60+m}
function plannedMinutes(r){return Math.max(0,timeToMins(r.end)-timeToMins(r.start)-Number(r.breakMinutes||0))}
function weeksElapsed(l){const start=new Date(`${l.startDate}T12:00:00`),end=new Date(`${l.endDate}T12:00:00`),now=new Date(`${today()}T12:00:00`);if(now<start)return 0;const capped=now>end?end:now;return Math.max(0,(capped-start)/(7*86400000))}
function expectedMinutes(l){return Math.round(weeksElapsed(l)*6*60)}
function learnerRegisters(id){return state.registers.filter(r=>r.status==='completed'&&r.entries?.[id])}
function entryMinutes(r,e){if(!e)return 0;if(e.status!=='present')return Number(e.adjustment||0);const attended=Math.max(0,timeToMins(e.leave)-timeToMins(e.arrival)-Number(r.breakMinutes||0));return attended+Number(e.adjustment||0)}
function learnerActualMinutes(l){return Math.round(Number(l.pastHoursAdjustment||0)*60+learnerRegisters(l.id).reduce((sum,r)=>sum+entryMinutes(r,r.entries[l.id]),0))}
function learnerStats(l){const regs=learnerRegisters(l.id);const expected=expectedMinutes(l),actual=learnerActualMinutes(l);const present=regs.filter(r=>r.entries[l.id]?.status==='present').length;return{regs,expected,actual,balance:actual-expected,attendance:regs.length?Math.round(present/regs.length*100):0}}
function showPage(name){pages.forEach(p=>p.classList.toggle('active',p.dataset.page===name));nav.forEach(n=>n.classList.toggle('active',n.dataset.nav===name));window.scrollTo(0,0);if(name==='learners')renderLearners();if(name==='classes')renderClasses();if(name==='logs')renderLogs()}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)}

function renderHome(){
 $('statLearners').textContent=state.learners.length;$('statClasses').textContent=state.classes.length;$('statLogs').textContent=state.registers.filter(r=>r.status==='completed').length;
 const total=state.registers.filter(r=>r.status==='completed').reduce((s,r)=>s+plannedMinutes(r),0);$('statHours').textContent=minsText(total);
}
function renderLearners(){const list=$('learnerList');$('learnerEmpty').hidden=state.learners.length>0;list.innerHTML=state.learners.map(l=>{const s=learnerStats(l);return`<article class="card"><div class="card-main"><h3>${esc(l.name)}</h3><div class="meta">${dateText(l.startDate)} – ${dateText(l.endDate)} · Expected ${minsText(s.expected)} · Completed ${minsText(s.actual)}</div></div><div class="card-actions"><button class="secondary" data-open-learner="${l.id}">Open profile</button><button class="ghost" data-edit-learner="${l.id}">Edit</button><button class="danger" data-delete-learner="${l.id}">Delete</button></div></article>`}).join('')}
function openLearnerDialog(id=null){const l=state.learners.find(x=>x.id===id);$('learnerId').value=l?.id||'';$('learnerName').value=l?.name||'';$('learnerStart').value=l?.startDate||today();$('learnerEnd').value=l?.endDate||new Date(Date.now()+365*86400000).toISOString().slice(0,10);$('learnerAdjustment').value=l?.pastHoursAdjustment||0;$('learnerDialogTitle').textContent=l?'Edit learner':'Add learner';$('learnerDialog').showModal()}
function renderLearnerProfile(){const l=state.learners.find(x=>x.id===currentLearnerId);if(!l)return showPage('learners');const s=learnerStats(l);$('learnerProfile').innerHTML=`<div class="profile-hero"><div><p class="eyebrow">LEARNER PROFILE</p><h2>${esc(l.name)}</h2><div class="meta">${dateText(l.startDate)} – ${dateText(l.endDate)} · 6 hours per week</div></div><button class="secondary" data-edit-learner="${l.id}">Edit learner</button></div><div class="profile-stats"><article class="summary-card"><span>Expected by today</span><strong>${minsText(s.expected)}</strong></article><article class="summary-card"><span>Completed</span><strong>${minsText(s.actual)}</strong></article><article class="summary-card"><span>Hours position</span><strong>${s.balance>=0?'+':''}${minsText(s.balance)}</strong></article><article class="summary-card"><span>Attendance</span><strong>${s.attendance}%</strong></article></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Class</th><th>Status</th><th>Arrival</th><th>Leave</th><th>Hours added</th><th>Note</th></tr></thead><tbody>${s.regs.length?s.regs.sort((a,b)=>b.date.localeCompare(a.date)).map(r=>{const e=r.entries[l.id],c=state.classes.find(x=>x.id===r.classId);return`<tr><td>${dateText(r.date)}</td><td>${esc(c?.name||r.className||'Deleted class')}</td><td class="status ${e.status}">${e.status.replace(/^./,x=>x.toUpperCase())}</td><td>${e.arrival||'—'}</td><td>${e.leave||'—'}</td><td>${minsText(entryMinutes(r,e))}</td><td>${esc(e.note||'')}</td></tr>`}).join(''):'<tr><td colspan="7">No completed registers for this learner.</td></tr>'}</tbody></table></div>`}

function renderClasses(){const list=$('classList');$('classEmpty').hidden=state.classes.length>0;list.innerHTML=state.classes.map(c=>{const active=state.registers.find(r=>r.classId===c.id&&r.status==='open');const logs=state.registers.filter(r=>r.classId===c.id&&r.status==='completed').length;return`<article class="card"><div class="card-main"><h3>${esc(c.name)}</h3><div class="meta">${esc(c.location||'No location')} · ${c.learnerIds.length} learners · ${logs} saved registers${active?' · Register in progress':''}</div></div><div class="card-actions"><button class="secondary" data-open-class="${c.id}">Open class</button><button class="ghost" data-edit-class="${c.id}">Edit</button><button class="danger" data-delete-class="${c.id}">Delete</button></div></article>`}).join('')}
function openClassDialog(id=null){const c=state.classes.find(x=>x.id===id);$('classId').value=c?.id||'';$('className').value=c?.name||'';$('classLocation').value=c?.location||'';$('classStart').value=c?.defaultStart||'09:00';$('classEnd').value=c?.defaultEnd||'15:30';$('classDialogTitle').textContent=c?'Edit class':'Create class';$('classDialog').showModal()}
function renderClassDetail(){const c=state.classes.find(x=>x.id===currentClassId);if(!c)return showPage('classes');const learners=c.learnerIds.map(id=>state.learners.find(l=>l.id===id)).filter(Boolean);const active=state.registers.find(r=>r.classId===c.id&&r.status==='open');const logs=state.registers.filter(r=>r.classId===c.id&&r.status==='completed').sort((a,b)=>b.date.localeCompare(a.date));$('classDetail').innerHTML=`<div class="profile-hero"><div><p class="eyebrow">CLASS</p><h2>${esc(c.name)}</h2><div class="meta">${esc(c.location||'No location')} · Default ${c.defaultStart}–${c.defaultEnd}</div></div><div class="card-actions"><button class="secondary" data-manage-class-learners>Manage learners</button>${active?`<button class="primary" data-open-register="${active.id}">Continue register</button>`:`<button class="primary" data-start-register>Start register</button>`}</div></div><div class="profile-stats"><article class="summary-card"><span>Learners</span><strong>${learners.length}</strong></article><article class="summary-card"><span>Completed registers</span><strong>${logs.length}</strong></article><article class="summary-card"><span>Default start</span><strong>${c.defaultStart}</strong></article><article class="summary-card"><span>Default finish</span><strong>${c.defaultEnd}</strong></article></div><h3>Learners in this class</h3><div class="card-list">${learners.length?learners.map(l=>`<article class="card"><div><strong>${esc(l.name)}</strong><div class="meta">${dateText(l.startDate)} – ${dateText(l.endDate)}</div></div><button class="secondary" data-open-learner="${l.id}">Profile</button></article>`).join(''):'<div class="empty"><p>No learners added to this class.</p></div>'}</div><h3>Recent register logs</h3><div class="card-list">${logs.length?logs.slice(0,5).map(r=>logCard(r)).join(''):'<div class="empty"><p>No completed registers for this class.</p></div>'}</div>`}
function manageClassLearners(){const c=state.classes.find(x=>x.id===currentClassId);$('classLearnerChoices').innerHTML=state.learners.length?state.learners.map(l=>`<label class="choice"><input type="checkbox" value="${l.id}" ${c.learnerIds.includes(l.id)?'checked':''}><span><strong>${esc(l.name)}</strong><small>${dateText(l.startDate)} – ${dateText(l.endDate)}</small></span></label>`).join(''):'<div class="empty"><p>Create learners in the learner section first.</p></div>';$('classLearnersDialog').showModal()}

function openRegisterDialog(){const c=state.classes.find(x=>x.id===currentClassId);if(!c.learnerIds.length)return toast('Add learners to the class first');$('registerDate').value=today();$('registerStart').value=c.defaultStart;$('registerEnd').value=c.defaultEnd;$('registerBreak').value=30;$('registerDialog').showModal()}
function renderLiveRegister(){const r=state.registers.find(x=>x.id===currentRegisterId),c=state.classes.find(x=>x.id===r?.classId);if(!r||!c)return;const learners=r.learnerIds.map(id=>state.learners.find(l=>l.id===id)).filter(Boolean);const totals={present:0,authorised:0,unauthorised:0,pending:0};learners.forEach(l=>totals[r.entries[l.id]?.status||'pending']++);$('liveRegister').innerHTML=`<div class="profile-hero"><div><p class="eyebrow">LIVE REGISTER</p><h2>${esc(c.name)}</h2><div class="meta">${dateText(r.date)} · ${r.start}–${r.end} · ${r.breakMinutes} min break</div></div><button class="primary" data-complete-register>Complete and save register</button></div><div class="register-summary"><article class="summary-card"><span>Present</span><strong>${totals.present}</strong></article><article class="summary-card"><span>Authorised</span><strong>${totals.authorised}</strong></article><article class="summary-card"><span>Unauthorised</span><strong>${totals.unauthorised}</strong></article><article class="summary-card"><span>Not marked</span><strong>${totals.pending}</strong></article></div><div class="register-list">${learners.map(l=>{const e=r.entries[l.id],status=e?.status||'pending';return`<div class="register-row"><div class="name">${esc(l.name)}</div><div><span class="meta">Status</span><br><button class="status-btn ${status}" data-mark-learner="${l.id}">${status==='pending'?'Mark':status.replace(/^./,x=>x.toUpperCase())}</button></div><div><span class="meta">Arrival</span><br><strong>${e?.arrival||'—'}</strong></div><div><span class="meta">Leave</span><br><strong>${e?.leave||'—'}</strong></div><div><span class="meta">Hours</span><br><strong>${e?minsText(entryMinutes(r,e)):'—'}</strong></div><button class="ghost" data-mark-learner="${l.id}">Edit</button></div>`}).join('')}</div>`}
function openMarkDialog(id){const r=state.registers.find(x=>x.id===currentRegisterId),l=state.learners.find(x=>x.id===id),e=r.entries[id];$('markLearnerId').value=id;$('markLearnerName').textContent=l.name;$('markStatus').value=e?.status||'present';$('markArrival').value=e?.arrival||r.start;$('markLeave').value=e?.leave||r.end;$('markAdjustment').value=e?.adjustment||0;$('markNote').value=e?.note||'';toggleTimeFields();$('markDialog').showModal()}
function toggleTimeFields(){$('timeFields').hidden=$('markStatus').value!=='present'}
function completeRegister(){const r=state.registers.find(x=>x.id===currentRegisterId);const pending=r.learnerIds.filter(id=>!r.entries[id]);if(pending.length&&!confirm(`${pending.length} learner(s) are not marked. Save them as unauthorised absence?`))return;pending.forEach(id=>r.entries[id]={status:'unauthorised',arrival:'',leave:'',adjustment:0,note:'Not marked when register was completed'});r.status='completed';r.completedAt=new Date().toISOString();save();renderLogs();toast('Register completed and saved');showPage('logs')}

function logCard(r){const c=state.classes.find(x=>x.id===r.classId);const vals=Object.values(r.entries||{});return`<article class="card"><div class="card-main"><h3>${esc(c?.name||r.className||'Deleted class')}</h3><div class="meta">${dateText(r.date)} · ${vals.filter(e=>e.status==='present').length} present · ${vals.filter(e=>e.status==='unauthorised').length} unauthorised</div></div><button class="secondary" data-open-log="${r.id}">View log</button></article>`}
function renderLogs(){const logs=state.registers.filter(r=>r.status==='completed').sort((a,b)=>(b.date+b.completedAt).localeCompare(a.date+a.completedAt));$('logEmpty').hidden=logs.length>0;$('logList').innerHTML=logs.map(logCard).join('')}
function renderLogDetail(){const r=state.registers.find(x=>x.id===currentRegisterId),c=state.classes.find(x=>x.id===r?.classId);if(!r)return showPage('logs');const learners=r.learnerIds.map(id=>state.learners.find(l=>l.id===id)||{id,name:'Deleted learner'});$('logDetail').innerHTML=`<div class="profile-hero"><div><p class="eyebrow">REGISTER LOG</p><h2>${esc(c?.name||r.className||'Deleted class')}</h2><div class="meta">${dateText(r.date)} · ${r.start}–${r.end} · Completed ${new Date(r.completedAt).toLocaleString('en-GB')}</div></div><button class="danger" data-delete-log="${r.id}">Delete log</button></div><div class="table-wrap"><table><thead><tr><th>Learner</th><th>Status</th><th>Arrival</th><th>Leave</th><th>Minutes</th><th>Adjustment</th><th>Note</th></tr></thead><tbody>${learners.map(l=>{const e=r.entries[l.id]||{};return`<tr><td>${esc(l.name)}</td><td class="status ${e.status}">${esc(e.status||'')}</td><td>${e.arrival||'—'}</td><td>${e.leave||'—'}</td><td>${minsText(entryMinutes(r,e))}</td><td>${Number(e.adjustment||0)} min</td><td>${esc(e.note||'')}</td></tr>`}).join('')}</tbody></table></div>`}

$('learnerForm').addEventListener('submit',e=>{e.preventDefault();const id=$('learnerId').value,name=$('learnerName').value.trim();if(!name)return;if(new Date($('learnerEnd').value)<new Date($('learnerStart').value))return toast('End date must be after start date');const data={name,startDate:$('learnerStart').value,endDate:$('learnerEnd').value,pastHoursAdjustment:Number($('learnerAdjustment').value||0)};if(id)Object.assign(state.learners.find(l=>l.id===id),data);else state.learners.push({id:uid('learner'),...data,createdAt:new Date().toISOString()});state.learners.sort((a,b)=>a.name.localeCompare(b.name));save();$('learnerDialog').close();renderLearners();if(currentLearnerId===id)renderLearnerProfile();toast(id?'Learner updated':'Learner created')});
$('classForm').addEventListener('submit',e=>{e.preventDefault();if(timeToMins($('classEnd').value)<=timeToMins($('classStart').value))return toast('Finish time must be after start time');const id=$('classId').value,data={name:$('className').value.trim(),location:$('classLocation').value.trim(),defaultStart:$('classStart').value,defaultEnd:$('classEnd').value};if(id)Object.assign(state.classes.find(c=>c.id===id),data);else state.classes.push({id:uid('class'),learnerIds:[],...data,createdAt:new Date().toISOString()});save();$('classDialog').close();renderClasses();if(currentClassId===id)renderClassDetail();toast(id?'Class updated':'Class created')});
$('classLearnersForm').addEventListener('submit',e=>{e.preventDefault();const c=state.classes.find(x=>x.id===currentClassId);c.learnerIds=[...$('classLearnerChoices').querySelectorAll('input:checked')].map(i=>i.value);save();$('classLearnersDialog').close();renderClassDetail();toast('Class list updated')});
$('registerForm').addEventListener('submit',e=>{e.preventDefault();if(timeToMins($('registerEnd').value)<=timeToMins($('registerStart').value))return toast('Finish time must be after start time');const c=state.classes.find(x=>x.id===currentClassId);const r={id:uid('register'),classId:c.id,className:c.name,date:$('registerDate').value,start:$('registerStart').value,end:$('registerEnd').value,breakMinutes:Number($('registerBreak').value||0),learnerIds:[...c.learnerIds],entries:{},status:'open',createdAt:new Date().toISOString()};state.registers.push(r);currentRegisterId=r.id;save();$('registerDialog').close();renderLiveRegister();showPage('live-register')});
$('markForm').addEventListener('submit',e=>{e.preventDefault();const r=state.registers.find(x=>x.id===currentRegisterId),id=$('markLearnerId').value,status=$('markStatus').value;const entry={status,arrival:status==='present'?$('markArrival').value:'',leave:status==='present'?$('markLeave').value:'',adjustment:Number($('markAdjustment').value||0),note:$('markNote').value.trim()};if(status==='present'&&timeToMins(entry.leave)<timeToMins(entry.arrival))return toast('Leave time must be after arrival time');r.entries[id]=entry;save();$('markDialog').close();renderLiveRegister();toast('Attendance saved')});
$('markStatus').addEventListener('change',toggleTimeFields);

document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.nav)showPage(b.dataset.nav);if(b.dataset.go)showPage(b.dataset.go);if(b.dataset.back)showPage(b.dataset.back);if(b.hasAttribute('data-close'))b.closest('dialog')?.close();if(b.id==='addLearnerBtn'||b.hasAttribute('data-new-learner'))openLearnerDialog();if(b.dataset.editLearner)openLearnerDialog(b.dataset.editLearner);if(b.dataset.openLearner){currentLearnerId=b.dataset.openLearner;renderLearnerProfile();showPage('learner-profile')}if(b.dataset.deleteLearner){const l=state.learners.find(x=>x.id===b.dataset.deleteLearner);if(confirm(`Delete ${l.name}?`)){state.learners=state.learners.filter(x=>x.id!==l.id);state.classes.forEach(c=>c.learnerIds=c.learnerIds.filter(id=>id!==l.id));save();renderLearners()}}if(b.id==='addClassBtn'||b.hasAttribute('data-new-class'))openClassDialog();if(b.dataset.editClass)openClassDialog(b.dataset.editClass);if(b.dataset.openClass){currentClassId=b.dataset.openClass;renderClassDetail();showPage('class-detail')}if(b.dataset.deleteClass){const c=state.classes.find(x=>x.id===b.dataset.deleteClass);if(confirm(`Delete ${c.name}? Completed register logs will remain.`)){state.classes=state.classes.filter(x=>x.id!==c.id);save();renderClasses()}}if(b.hasAttribute('data-manage-class-learners'))manageClassLearners();if(b.hasAttribute('data-start-register'))openRegisterDialog();if(b.dataset.openRegister){currentRegisterId=b.dataset.openRegister;renderLiveRegister();showPage('live-register')}if(b.dataset.markLearner)openMarkDialog(b.dataset.markLearner);if(b.hasAttribute('data-complete-register'))completeRegister();if(b.id==='backFromRegister'){renderClassDetail();showPage('class-detail')}if(b.dataset.openLog){currentRegisterId=b.dataset.openLog;renderLogDetail();showPage('log-detail')}if(b.dataset.deleteLog){if(confirm('Delete this register log?')){state.registers=state.registers.filter(r=>r.id!==b.dataset.deleteLog);save();renderLogs();showPage('logs')}}});

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=3.9', { updateViaCache: 'none' }).catch(()=>{}));
renderHome();renderLearners();renderClasses();renderLogs();showPage('home');
