const KEY='assessorplus_timed_demo_v1';
const $=id=>document.getElementById(id); const uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{learners:[],classes:[],logs:[],live:null,demoTime:null,creditUses:[],assessmentTemplates:[],assessmentRecords:[],reviewSnapshots:[],reviews:[]};if(!Array.isArray(state.reviewSnapshots))state.reviewSnapshots=[];if(!Array.isArray(state.reviews))state.reviews=[];if(!Array.isArray(state.creditUses))state.creditUses=[];if(!Array.isArray(state.assessmentTemplates))state.assessmentTemplates=[];if(!Array.isArray(state.assessmentRecords))state.assessmentRecords=[]; state.learners.forEach(l=>{if(l.withdrawn===undefined)l.withdrawn=false;if(l.withdrawn&& !l.withdrawnAt)l.withdrawnAt=new Date().toISOString();if(!Array.isArray(l.holidays))l.holidays=[];if(!Number.isFinite(Number(l.bankAdjustment)))l.bankAdjustment=0;if(!Number.isFinite(Number(l.dailyHours)))l.dailyHours=Number(l.weekly)||6;if(!Array.isArray(l.attendanceDays)||!l.attendanceDays.length){let assigned=state.classes.filter(c=>(c.learnerIds||[]).includes(l.id)).map(c=>Number(c.weekday)).filter(Number.isFinite);l.attendanceDays=[...new Set(assigned.length?assigned:[new Date().getDay()])]}}); state.classes.forEach(c=>{if(!Array.isArray(c.holidays))c.holidays=[];if(c.weekday===undefined||c.weekday===null){let names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];let found=names.findIndex(n=>(c.name||'').toLowerCase().includes(n.toLowerCase()));c.weekday=found>=0?found:new Date().getDay()}}); state.logs.forEach((log,i)=>{if(!log.id)log.id=uid('reglog')+'_'+i;if(log.sentAt===undefined)log.sentAt=null}); if(state.live){if(!state.live.present)state.live.present={};if(!state.live.events)state.live.events={};state.live.learnerIds.forEach(id=>{if(!Array.isArray(state.live.events[id]))state.live.events[id]=[];if(typeof state.live.present[id]!=='boolean')state.live.present[id]=false})} state.learners=sortedLearners(state.learners);localStorage.setItem(KEY,JSON.stringify(state)); let editingLearner=null,creditLearnerId=null,currentLearnerTab='active',editingClass=null,tempPeriods=[],tempSessions=[],tempHolidays=[],tempClassHolidays=[],editingLogId=null,currentLogTab='unsent',selectedLogIds=new Set(),selectedLearnerIds=new Set(),assessmentView='home',editingTemplateId=null,tempCriteria=[],editingCriterionId=null,editingAssessmentId=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function openM(id){$(id).classList.add('open')} function closeM(id){$(id).classList.remove('open')}
function dateISO(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function dateFmt(x){if(!x)return'—';return new Date(x+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function minText(n){n=Math.round(Number(n)||0);let sign=n<0?'-':'';n=Math.abs(n);return `${sign}${Math.floor(n/60)}h ${n%60}m`}
function timeMin(t){let [h,m]=(t||'00:00').split(':').map(Number);return h*60+m}
function now(){return state.demoTime?new Date(state.demoTime):new Date()}
function nowMinutes(){let d=now();return d.getHours()*60+d.getMinutes()+d.getSeconds()/60}
function nowTime(){return now().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function learnerName(id){let l=state.learners.find(x=>x.id===id);return l?`${l.first} ${l.last}`:'Removed learner'}
function sortedLearners(list=state.learners){return [...list].sort((a,b)=>(`${a.last||''} ${a.first||''}`).localeCompare(`${b.last||''} ${b.first||''}`,undefined,{sensitivity:'base'}))}
function isActiveLearner(l){return !!l&&!l.withdrawn}
function activeLearners(){return state.learners.filter(isActiveLearner)}
function setLearnerTab(tab){currentLearnerTab=tab==='withdrawn'?'withdrawn':'active';selectedLearnerIds.clear();$('activeLearnerTab')?.classList.toggle('active',currentLearnerTab==='active');$('withdrawnLearnerTab')?.classList.toggle('active',currentLearnerTab==='withdrawn');renderLearners()}
function dayStart(v){return new Date(v+'T00:00:00')}
function dayAfter(v){let d=dayStart(v);d.setDate(d.getDate()+1);return d}
function courseWindow(l){if(!l.startDate)return null;let start=dayStart(l.startDate),todayEnd=dayAfter(dateISO());let end=l.endDate?dayAfter(l.endDate):todayEnd;if(end>todayEnd)end=todayEnd;if(end<=start)return null;return{start,end}}
function learnerHolidayRanges(l){let own=(l.holidays||[]).map(h=>({start:h.start,end:h.end,label:h.label||'Holiday'}));let classRanges=state.classes.filter(c=>(c.learnerIds||[]).includes(l.id)).flatMap(c=>(c.holidays||[]).map(h=>({start:h.start,end:h.end,label:h.label||`${c.name} holiday`})));return [...own,...classRanges].filter(h=>h.start&&h.end)}
function holidayOverlapMinutes(l){let w=courseWindow(l);if(!w)return 0;let ranges=learnerHolidayRanges(l).map(h=>({a:Math.max(w.start.getTime(),dayStart(h.start).getTime()),b:Math.min(w.end.getTime(),dayAfter(h.end).getTime())})).filter(x=>x.b>x.a).sort((x,y)=>x.a-y.a);let merged=[];for(let r of ranges){let last=merged[merged.length-1];if(!last||r.a>last.b)merged.push({...r});else last.b=Math.max(last.b,r.b)}return merged.reduce((sum,r)=>sum+(r.b-r.a)/60000,0)}
function isDateInLearnerHoliday(l,date){return learnerHolidayRanges(l).some(h=>h.start&&h.end&&date>=h.start&&date<=h.end)}
function expectedAttendanceDates(l){let w=courseWindow(l);if(!w)return[];let selected=new Set((l.attendanceDays||[]).map(Number));let dates=[];for(let d=new Date(w.start);d<w.end;d.setDate(d.getDate()+1)){let iso=dateISO(d);if(selected.has(d.getDay())&&!isDateInLearnerHoliday(l,iso))dates.push(iso)}return dates}
function expectedMinutes(l){return expectedAttendanceDates(l).length*(Number(l.dailyHours)||0)*60}
function pausedExpectedMinutes(l){let w=courseWindow(l);if(!w)return 0;let selected=new Set((l.attendanceDays||[]).map(Number));let count=0;for(let d=new Date(w.start);d<w.end;d.setDate(d.getDate()+1)){let iso=dateISO(d);if(selected.has(d.getDay())&&isDateInLearnerHoliday(l,iso))count++}return count*(Number(l.dailyHours)||0)*60}
function attendanceDaysText(l){let names=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];return (l.attendanceDays||[]).map(Number).sort((a,b)=>(a||7)-(b||7)).map(d=>names[d]).join(', ')||'No days selected'}
function learnerLogs(id){return state.logs.filter(log=>log.results?.some(r=>r.learnerId===id))}
function actualCompletedMinutes(l){return Math.round((Number(l.pastHours)||0)*60+learnerLogs(l.id).reduce((s,log)=>s+(log.results.find(r=>r.learnerId===l.id)?.creditedMinutes||0),0))}
function learnerCreditUses(id){return state.creditUses.filter(x=>x.learnerId===id)}
function creditsUsedMinutes(id){return Math.round(learnerCreditUses(id).reduce((s,x)=>s+(Number(x.minutes)||0),0))}
function completedMinutes(l){return actualCompletedMinutes(l)+creditsUsedMinutes(l.id)}
function resultArrivalBankMinutes(log,result){if(!result||result.holiday)return 0;let periods=log.periods||[];return Math.round((result.details||[]).reduce((sum,d)=>{let p=periods.find(x=>x.id===d.periodId);if(!p||p.type!=='session'||!Array.isArray(d.segments)||!d.segments.length)return sum;let arrivals=d.segments.map(x=>Number(x.inMinute)).filter(Number.isFinite);if(!arrivals.length)return sum;let first=Math.min(...arrivals);return sum+(timeMin(p.start)-first)},0))}
function grossSavedBankMinutes(id){let l=state.learners.find(x=>x.id===id);if(!l)return 0;return Math.round((Number(l.bankAdjustment)||0)+learnerLogs(id).reduce((sum,log)=>{let r=log.results.find(x=>x.learnerId===id);return sum+resultArrivalBankMinutes(log,r)},0))}
function savedBankMinutes(id){return grossSavedBankMinutes(id)-creditsUsedMinutes(id)}
function liveBankDelta(id){let live=state.live;if(!live||isLearnerOnHoliday(id,live.date,live.classId))return 0;return Math.round(live.periods.filter(p=>p.type==='session').reduce((sum,p)=>{let rec=normaliseSessionRecord(live.checkins?.[p.id]?.[id]);if(!rec.segments.length)return sum;let arrivals=rec.segments.map(x=>Number(x.inMinute)).filter(Number.isFinite);return arrivals.length?sum+(timeMin(p.start)-Math.min(...arrivals)):sum},0))}
function learnerBankMinutes(id,includeLive=true){return savedBankMinutes(id)+(includeLive?liveBankDelta(id):0)}
function bankText(n){n=Math.round(Number(n)||0);let sign=n>0?'+':n<0?'-':'';n=Math.abs(n);return `${sign}${Math.floor(n/60)}h ${n%60}m`}
function bankClass(n){return n>0?'bank-positive':n<0?'bank-negative':'bank-zero'}
function attendanceStats(id){let l=state.learners.find(x=>x.id===id);if(!l)return{expected:0,actual:0,credits:0,completed:0,percent:0};let expected=Math.round(expectedMinutes(l)),actual=actualCompletedMinutes(l),credits=creditsUsedMinutes(id),completed=actual+credits;return{expected,actual,credits,completed,percent:expected?Math.min(100,Math.round(completed/expected*1000)/10):0}}
function resultSessionMetrics(log,result){let out={lateSessions:0,lateMinutes:0,absentSessions:0,absentMinutes:0,eligibleCreditMinutes:0};if(!result||result.holiday)return out;for(let p of (log.periods||[]).filter(x=>x.type==='session')){let duration=Math.max(0,timeMin(p.end)-timeMin(p.start));let d=(result.details||[]).find(x=>x.periodId===p.id);let segs=Array.isArray(d?.segments)?d.segments:[];let credited=Math.max(0,Number(d?.credited)||0);if(!segs.length){out.absentSessions++;out.absentMinutes+=duration;continue}let arrivals=segs.map(x=>Number(x.inMinute)).filter(Number.isFinite);if(arrivals.length){let late=Math.max(0,Math.min(...arrivals)-timeMin(p.start));if(late>0){out.lateSessions++;out.lateMinutes+=late}}let partialMiss=Math.max(0,duration-Math.min(duration,credited));out.absentMinutes+=partialMiss;out.eligibleCreditMinutes+=partialMiss}Object.keys(out).forEach(k=>out[k]=Math.round(out[k]));return out}
function learnerSessionMetrics(id){return learnerLogs(id).reduce((total,log)=>{let r=(log.results||[]).find(x=>x.learnerId===id),m=resultSessionMetrics(log,r);total.lateSessions+=m.lateSessions;total.lateMinutes+=m.lateMinutes;total.absentSessions+=m.absentSessions;total.absentMinutes+=m.absentMinutes;total.eligibleCreditMinutes+=m.eligibleCreditMinutes;return total},{lateSessions:0,lateMinutes:0,absentSessions:0,absentMinutes:0,eligibleCreditMinutes:0})}
function remainingEligibleCreditMinutes(id){return Math.max(0,learnerSessionMetrics(id).eligibleCreditMinutes-creditsUsedMinutes(id))}
function openAttendanceCredit(id){let l=state.learners.find(x=>x.id===id);if(!l)return;let available=Math.max(0,learnerBankMinutes(id,false)),eligible=remainingEligibleCreditMinutes(id);if(available<=0)return alert('This learner has no available minute-bank credits.');if(eligible<=0)return alert('There is no eligible lateness or partial missed time to cover.');creditLearnerId=id;$('creditMinutes').value=Math.min(available,eligible);$('creditMinutes').max=Math.min(available,eligible);$('creditReason').value='';$('creditSummary').innerHTML=`<strong>${esc(l.first+' '+l.last)}</strong><div class="row-meta">Available bank: ${bankText(available)} · Eligible timing shortfall: ${minText(eligible)} · Maximum now: ${minText(Math.min(available,eligible))}</div>`;openM('creditModal')}
function saveAttendanceCredit(){let id=creditLearnerId,l=state.learners.find(x=>x.id===id);if(!l)return;let available=Math.max(0,learnerBankMinutes(id,false)),eligible=remainingEligibleCreditMinutes(id),max=Math.min(available,eligible),minutes=Math.round(Number($('creditMinutes').value)||0),reason=$('creditReason').value.trim();if(minutes<1||minutes>max)return alert(`Enter between 1 and ${max} minutes.`);if(!reason)return alert('Enter a reason for applying the credits.');state.creditUses.push({id:uid('credit'),learnerId:id,minutes,reason,appliedAt:new Date().toISOString(),appliedBy:'Tutor'});closeM('creditModal');save();openProfile(id)}
function deleteAttendanceCredit(id,learnerId){if(!confirm('Remove this attendance-credit entry?'))return;state.creditUses=state.creditUses.filter(x=>x.id!==id);save();openProfile(learnerId)}
function pdfSafeText(value){return String(value??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,'').replace(/([\\()])/g,'\\$1')}
function wrapPdfText(text,max=82){let words=String(text??'').split(/\s+/),lines=[],line='';for(let word of words){let next=line?line+' '+word:word;if(next.length>max&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines.length?lines:['']}
function buildTextPdf(title,sections){let lines=[{text:title,size:17,bold:true},...sections];let pages=[],page=[],y=800;for(let item of lines){if(item.pageBreak){if(page.length){pages.push(page);page=[]}y=800;continue}if(item.gap){y-=item.gap;continue}let wrapped=wrapPdfText(item.text,item.max||(item.size>=16?62:86));for(let text of wrapped){let leading=(item.size||10)+4;if(y-leading<45){pages.push(page);page=[];y=800}page.push({text,size:item.size||10,bold:!!item.bold,y});y-=leading}}if(page.length||!pages.length)pages.push(page);let objects=[];let add=o=>{objects.push(o);return objects.length};let fontRegular=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let fontBold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');let pageRefs=[];let contentRefs=[];for(let pg of pages){let commands=['BT'];for(let row of pg){commands.push(`/${row.bold?'F2':'F1'} ${row.size} Tf 50 ${row.y} Td (${pdfSafeText(row.text)}) Tj ${-50} ${-row.y} Td`)}commands.push('ET');let stream=commands.join('\n');contentRefs.push(add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`));pageRefs.push(add(''))}let pagesRef=add('');let catalogRef=add(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`);pageRefs.forEach((ref,i)=>objects[ref-1]=`<< /Type /Page /Parent ${pagesRef} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentRefs[i]} 0 R >>`);objects[pagesRef-1]=`<< /Type /Pages /Kids [${pageRefs.map(r=>r+' 0 R').join(' ')}] /Count ${pageRefs.length} >>`;let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});let xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length+1} /Root ${catalogRef} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function downloadLearnerPdf(id){let l=state.learners.find(x=>x.id===id);if(!l)return;let a=attendanceStats(id),m=learnerSessionMetrics(id),bank=learnerBankMinutes(id,false),logs=learnerLogs(id).slice().sort((x,y)=>String(y.date).localeCompare(String(x.date)));let sections=[{text:`Generated: ${new Date().toLocaleString('en-GB')}`,size:9},{gap:8},{text:'Learner summary',size:13,bold:true},{text:`Course dates: ${dateFmt(l.startDate)} to ${dateFmt(l.endDate)}`},{text:`Expected schedule: ${Number(l.dailyHours)||0} hours on ${attendanceDaysText(l)}`},{text:`Expected by today: ${minText(a.expected)}`},{text:`Actually attended: ${minText(a.actual)}`},{text:`Attendance credits applied: ${minText(a.credits)}`},{text:`Official attendance after credits: ${a.percent}%`},{text:`Available minute bank: ${bankText(bank)}`},{text:`Late sessions: ${m.lateSessions}`},{text:`Total lateness: ${minText(m.lateMinutes)}`},{text:`Fully absent sessions: ${m.absentSessions}`},{text:`Total missed learning time: ${minText(m.absentMinutes)}`}];let uses=learnerCreditUses(id).slice().sort((a,b)=>String(b.appliedAt).localeCompare(String(a.appliedAt)));sections.push({gap:10},{text:'Attendance-credit audit trail',size:13,bold:true});if(!uses.length)sections.push({text:'No attendance credits applied.'});for(let u of uses)sections.push({text:`${new Date(u.appliedAt).toLocaleDateString('en-GB')}: ${minText(u.minutes)} applied - ${u.reason}`});sections.push({gap:10},{text:'Register history',size:13,bold:true});if(!logs.length)sections.push({text:'No completed registers.'});for(let log of logs){let r=(log.results||[]).find(x=>x.learnerId===id),rm=resultSessionMetrics(log,r);sections.push({gap:6},{text:`${dateFmt(log.date)} - ${log.className}`,size:11,bold:true},{text:r?.holiday?'On holiday':`Attended ${minText(r?.creditedMinutes||0)} of ${minText(log.plannedMinutes)} (${logAttendancePercent(log,r)})`},{text:r?.holiday?'No lateness or absence recorded.':`Late ${rm.lateSessions} session(s), ${minText(rm.lateMinutes)} late; absent ${rm.absentSessions} full session(s), ${minText(rm.absentMinutes)} missed.`})}let blob=buildTextPdf(`${l.first} ${l.last} - Individual Attendance Record`,sections);let url=URL.createObjectURL(blob),aEl=document.createElement('a');aEl.href=url;aEl.download=`${l.first}-${l.last}-Attendance-Record.pdf`.replace(/[^a-z0-9._-]/gi,'-');document.body.appendChild(aEl);aEl.click();aEl.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function isClassOnHoliday(classId,date=state.live?.date||dateISO(now())){let c=state.classes.find(x=>x.id===classId);return !!c&&(c.holidays||[]).some(h=>h.start&&h.end&&date>=h.start&&date<=h.end)}
function classHolidayReason(classId,date=state.live?.date||dateISO(now())){let c=state.classes.find(x=>x.id===classId);let h=(c?.holidays||[]).find(x=>x.start&&x.end&&date>=x.start&&date<=x.end);return h?.label||'Class holiday'}
function isLearnerOnHoliday(id,date=state.live?.date||dateISO(now()),classId=state.live?.classId){let l=state.learners.find(x=>x.id===id);let own=!!l&&(l.holidays||[]).some(h=>h.start&&h.end&&date>=h.start&&date<=h.end);return own||!!(classId&&isClassOnHoliday(classId,date))}
function holidayReason(id,date=state.live?.date||dateISO(now()),classId=state.live?.classId){let l=state.learners.find(x=>x.id===id);let h=(l?.holidays||[]).find(x=>x.start&&x.end&&date>=x.start&&date<=x.end);return h?.label||(classId&&isClassOnHoliday(classId,date)?classHolidayReason(classId,date):'Holiday')}

document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');renderAll()});

function selectedAttendanceDays(){return [...document.querySelectorAll('#attendanceDays input:checked')].map(x=>Number(x.value))}
function setSelectedAttendanceDays(days){let set=new Set((days||[]).map(Number));document.querySelectorAll('#attendanceDays input').forEach(x=>x.checked=set.has(Number(x.value)))}
function updateWeeklyExpectedSummary(){let days=selectedAttendanceDays().length,hours=Number($('ldh').value)||0;$('weeklyExpectedSummary').textContent=`${days} day${days===1?'':'s'} × ${hours}h = ${days*hours} expected hours per week`;if($('learnerModal').classList.contains('open'))renderHolidaySummary()}
