function clockText(total){total=((total%1440)+1440)%1440;return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function defaultSessions(){return[
{id:uid('s'),label:'Session 1',start:'09:00',end:'11:00',breakMinutes:30,breakLabel:'Break'},
{id:uid('s'),label:'Session 2',start:'11:30',end:'13:00',breakMinutes:60,breakLabel:'Lunch'},
{id:uid('s'),label:'Session 3',start:'14:00',end:'16:00',breakMinutes:0,breakLabel:'Break'}]}
function periodsToSessions(periods){let sessions=periods.filter(p=>p.type==='session');return sessions.map((p,i)=>{let next=sessions[i+1];let gap=next?Math.max(0,timeMin(next.start)-timeMin(p.end)):0;let br=periods.find(x=>x.type==='break'&&timeMin(x.start)>=timeMin(p.end)&&(!next||timeMin(x.end)<=timeMin(next.start)));return{id:p.id||uid('s'),label:p.label||`Session ${i+1}`,start:p.start,end:p.end,breakMinutes:gap,breakLabel:br?.label||(gap>=45?'Lunch':'Break')}})}
function recalcSessionStarts(){for(let i=1;i<tempSessions.length;i++){let prev=tempSessions[i-1];tempSessions[i].start=clockText(timeMin(prev.end)+(Number(prev.breakMinutes)||0))}}
function sessionsToPeriods(){recalcSessionStarts();let out=[];tempSessions.forEach((s,i)=>{out.push({id:s.id,type:'session',label:s.label||`Session ${i+1}`,start:s.start,end:s.end});if(i<tempSessions.length-1&&(Number(s.breakMinutes)||0)>0){out.push({id:uid('p'),type:'break',label:s.breakLabel||'Break',start:s.end,end:clockText(timeMin(s.end)+(Number(s.breakMinutes)||0))})}});return out}
function toggleRegisterTypeFields(){let recurring=$('crecurring')?.checked!==false;$('recurringDayField').style.display=recurring?'':'none';$('recurringRangeField').style.display=recurring?'':'none';$('oneOffDateField').style.display=recurring?'none':''}
function openClass(id=null){editingClass=id;let c=state.classes.find(x=>x.id===id);$('classTitle').textContent=c?'Edit register':'Create register';$('cn').value=c?.name||'';let recurring=c?.recurring!==false;$('crecurring').checked=recurring;$('cweekday').value=String(c?.weekday??new Date().getDay());$('conedate').value=c?.oneOffDate||dateISO(now());$('crecurstart').value=c?.recurringStart||dateISO(now());let defaultEnd=new Date(now());defaultEnd.setFullYear(defaultEnd.getFullYear()+1);$('crecurend').value=c?.recurringEnd||dateISO(defaultEnd);toggleRegisterTypeFields();tempSessions=c?.periods?periodsToSessions(JSON.parse(JSON.stringify(c.periods))):defaultSessions();tempClassHolidays=JSON.parse(JSON.stringify(c?.holidays||[]));recalcSessionStarts();renderScheduleRows();renderClassHolidayRows();if($('classLearnerSearch'))$('classLearnerSearch').value='';renderClassLearnerChecks(c?.learnerIds||[]);openM('classModal')}

function addClassHoliday(){tempClassHolidays.push({label:'Half term',start:'',end:''});renderClassHolidayRows()}
function updateClassHoliday(i,key,val){tempClassHolidays[i][key]=val;renderClassHolidaySummary()}
function removeClassHoliday(i){tempClassHolidays.splice(i,1);renderClassHolidayRows()}
function renderClassHolidayRows(){$('classHolidayRows').innerHTML=tempClassHolidays.length?tempClassHolidays.map((h,i)=>`<div class="holiday-row"><div class="field"><label>Reason</label><input value="${esc(h.label||'')}" oninput="updateClassHoliday(${i},'label',this.value)"></div><div class="field"><label>From</label><input type="date" value="${h.start||''}" onchange="updateClassHoliday(${i},'start',this.value)"></div><div class="field"><label>To</label><input type="date" value="${h.end||''}" onchange="updateClassHoliday(${i},'end',this.value)"></div><button class="btn small danger" onclick="removeClassHoliday(${i})">Remove</button></div>`).join(''):'<div class="empty" style="padding:16px">No class holiday periods added.</div>';renderClassHolidaySummary()}
function renderClassHolidaySummary(){let valid=tempClassHolidays.filter(h=>h.start&&h.end&&h.end>=h.start);let days=valid.reduce((n,h)=>n+Math.round((dayAfter(h.end)-dayStart(h.start))/86400000),0);$('classHolidaySummary').textContent=valid.length?`${valid.length} class holiday period${valid.length===1?'':'s'} · ${days} calendar day${days===1?'':'s'} paused for learners in this class.`:'This class currently has no paused dates.'}

function addSession(){let i=tempSessions.length;let prev=tempSessions[i-1];if(prev&&!(Number(prev.breakMinutes)>0))prev.breakMinutes=30;let start=prev?clockText(timeMin(prev.end)+(Number(prev.breakMinutes)||0)):'09:00';tempSessions.push({id:uid('s'),label:`Session ${i+1}`,start,end:clockText(timeMin(start)+90),breakMinutes:0,breakLabel:'Break'});renderScheduleRows()}
function updateSession(id,key,val){let x=tempSessions.find(s=>s.id===id);if(!x)return;x[key]=key==='breakMinutes'?Math.max(0,Number(val)||0):val;recalcSessionStarts();renderScheduleRows()}
function removeSession(id){tempSessions=tempSessions.filter(x=>x.id!==id);tempSessions.forEach((x,i)=>x.label=x.label||`Session ${i+1}`);recalcSessionStarts();renderScheduleRows()}
function renderScheduleRows(){recalcSessionStarts();let total=tempSessions.reduce((n,s)=>n+Math.max(0,timeMin(s.end)-timeMin(s.start)),0);$('scheduleRows').innerHTML=tempSessions.map((s,i)=>`<div class="schedule-row"><div class="field type"><label>Session name</label><input value="${esc(s.label)}" onchange="updateSession('${s.id}','label',this.value)"></div><div class="field"><label>${i===0?'Start':'Start (auto)'}</label><input type="time" value="${s.start}" ${i===0?`onchange="updateSession('${s.id}','start',this.value)"`:'readonly'}></div><div class="field"><label>End</label><input type="time" value="${s.end}" onchange="updateSession('${s.id}','end',this.value)"></div>${i<tempSessions.length-1?`<div class="field"><label>Break after</label><input type="text" class="ap-duration-field" readonly inputmode="none" data-duration-minutes="${Number(s.breakMinutes)||0}" data-session-id="${s.id}" value="${minText(Number(s.breakMinutes)||0)}"></div>`:'<div class="field"><label>Break after</label><input value="End of day" readonly></div>'}<button class="btn small danger" onclick="removeSession('${s.id}')">Remove</button></div>`).join('')+`<div class="card" style="margin:10px 0 14px"><div class="muted">Total teaching hours</div><div class="stat" style="font-size:24px">${minText(total)}</div></div>`}
function renderClassLearnerChecks(selectedIds=null){const box=$('classChecks');if(!box)return;const selected=new Set(selectedIds||[...box.querySelectorAll('input:checked')].map(x=>x.value));const q=($('classLearnerSearch')?.value||'').trim().toLowerCase();const learners=sortedLearners(state.learners.filter(l=>!l.withdrawn&&(l.first+' '+l.last).toLowerCase().includes(q)));box.innerHTML=learners.length?learners.map(l=>`<label class="check-card"><input type="checkbox" value="${l.id}" ${selected.has(String(l.id))||selected.has(l.id)?'checked':''}> ${esc(l.first+' '+l.last)}</label>`).join(''):`<div class="empty">${state.learners.length?'No learners match your search.':'Create learners first.'}</div>`}
function saveClass(){let name=$('cn').value.trim();if(!name)return alert('Enter a class name.');if(!tempSessions.length)return alert('Add at least one learning session.');let recurring=$('crecurring').checked!==false,oneOffDate=$('conedate').value,recurringStart=$('crecurstart').value,recurringEnd=$('crecurend').value;if(!recurring&&!oneOffDate)return alert('Choose the date for this one-off register.');if(recurring&&(!recurringStart||!recurringEnd||recurringEnd<recurringStart))return alert('Choose a valid recurring date range.');recalcSessionStarts();for(let s of tempSessions){if(timeMin(s.end)<=timeMin(s.start))return alert(`${s.label}: end time must be after ${s.start}.`)}let periods=sessionsToPeriods();tempPeriods=periods;let ids=[...$('classChecks').querySelectorAll('input:checked')].map(x=>x.value);for(let h of tempClassHolidays){if(!h.start||!h.end||h.end<h.start)return alert('Check each class holiday start and end date.')}let obj={id:editingClass||uid('cls'),name,recurring,weekday:recurring?Number($('cweekday').value):new Date(oneOffDate+'T12:00:00').getDay(),oneOffDate:recurring?'':oneOffDate,recurringStart:recurring?recurringStart:'',recurringEnd:recurring?recurringEnd:'',learnerIds:ids,periods,holidays:tempClassHolidays};if(editingClass)state.classes=state.classes.map(x=>x.id===editingClass?obj:x);else state.classes.push(obj);closeM('classModal');save()}
function deleteClass(id){let c=state.classes.find(x=>x.id===id);if(!c)return;if(!confirm(`Delete ${c.name}? Completed register logs will be kept.`))return;state.classes=state.classes.filter(x=>x.id!==id);if(state.live?.classId===id)state.live=null;save()}
function weekdayName(n){return ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][Number(n)]||'Unscheduled'}
function classStart(c){let sessions=(c.periods||[]).filter(p=>p.type==='session');return sessions.length?sessions[0].start:'—'}
function renderClasses(){let el=$('classList');el.innerHTML=state.classes.length?state.classes.map(c=>{let sessions=c.periods.filter(p=>p.type==='session'),planned=sessions.reduce((s,p)=>s+timeMin(p.end)-timeMin(p.start),0);let end=sessions.length?sessions[sessions.length-1].end:'—';let activeHoliday=(c.holidays||[]).find(h=>h.start&&h.end&&dateISO(now())>=h.start&&dateISO(now())<=h.end);let schedule=c.recurring===false?`One-off · ${dateFmt(c.oneOffDate)}`:`Recurring · ${weekdayName(c.weekday)} · ${dateFmt(c.recurringStart)} to ${dateFmt(c.recurringEnd)}`;return `<div class="compact-register-row"><div class="compact-register-line"><span class="compact-register-name">${esc(c.name)}</span><span class="compact-separator">-</span><span>${schedule} · ${classStart(c)}–${end} · ${(c.learnerIds||[]).filter(id=>isActiveLearner(state.learners.find(l=>String(l.id)===String(id)))).length} learners</span>${activeHoliday?' <span class="holiday-badge">On holiday</span>':''}</div><div class="row-actions compact-register-action"><button class="btn small dark" onclick="openClass('${c.id}')">Edit</button><button class="btn small danger" onclick="deleteClass('${c.id}')">Delete</button></div></div>`}).join(''):'<div class="empty">No registers created yet.</div>'}
function classRunsOnDate(c,date){if(c.recurring===false)return c.oneOffDate===date;if(c.recurringStart&&date<c.recurringStart)return false;if(c.recurringEnd&&date>c.recurringEnd)return false;return Number(c.weekday)===dayStart(date).getDay()}
function nextScheduledClass(todayDay){if(!state.classes.length)return null;let todayDate=dayStart(dateISO(now()));let ranked=state.classes.map(c=>{if(c.recurring===false){let target=dayStart(c.oneOffDate);let d=Math.round((target-todayDate)/86400000);return d>0?{c,d}:null}let d=(Number(c.weekday)-todayDay+7)%7;return {c,d:d===0?7:d}}).filter(Boolean).sort((a,b)=>a.d-b.d||timeMin(classStart(a.c))-timeMin(classStart(b.c)));return ranked[0]||null}
function startRegisterFor(classId){if(state.live)return alert('A register is already active. Complete or discard it first.');let c=state.classes.find(x=>x.id===classId);if(!c)return;let regDate=dateISO(now());if(isClassOnHoliday(c.id,regDate))return alert(`${c.name} is on holiday today (${classHolidayReason(c.id,regDate)}). No register is required.`);let learnerIds=(c.learnerIds||[]).filter(id=>isActiveLearner(state.learners.find(l=>String(l.id)===String(id)))),present={},events={};learnerIds.forEach(id=>{present[id]=false;events[id]=[]});state.live={id:uid('reg'),classId:c.id,className:c.name,date:regDate,periods:JSON.parse(JSON.stringify(c.periods)),learnerIds,present,events,startedAt:now().toISOString(),completed:false};save();document.querySelector('[data-page="registers"]')?.click();window.scrollTo({top:0,behavior:'instant'});processClock()}
function renderScheduledRegisters(){
let todayEl=$('scheduledRegisters'),upcomingEl=$('upcomingRegisters');if(!todayEl)return;
let day=now().getDay(),todayDate=dateISO(now());
let today=state.classes.filter(c=>classRunsOnDate(c,todayDate)).sort((a,b)=>timeMin(classStart(a))-timeMin(classStart(b)));
if(today.length){todayEl.innerHTML=today.map(c=>{let holiday=isClassOnHoliday(c.id,todayDate);let sessions=c.periods.filter(p=>p.type==='session');let start=sessions.length?sessions[0].start:'00:00',end=sessions.length?sessions[sessions.length-1].end:'00:00';let isLive=state.live?.classId===c.id&&state.live?.date===todayDate;let completedLog=state.logs.find(l=>l.classId===c.id&&l.date===todayDate);let minute=nowMinutes(),pastEnd=minute>=timeMin(end);let rowClass='compact-register-row',action='';if(isLive){rowClass+=' register-row-active';action='<button class="btn small primary" onclick="processClock()">Open register</button>'}else if(completedLog){rowClass+=' register-row-muted';action=`<button class="status-chip" onclick="openRegisterSection('logs')">Completed</button>`}else if(holiday){rowClass+=' register-row-muted';action='<span class="status-chip">On holiday</span>'}else if(pastEnd){rowClass+=' register-row-muted';action='<span class="status-chip status-missed">Missed</span>'}else{action=`<button class="btn small primary" onclick="startRegisterFor('${c.id}')">Start register</button>`}let type=c.recurring===false?'One-off':'Recurring';return `<div class="${rowClass}"><div class="compact-register-line"><span class="compact-register-name">${esc(c.name)}</span><span class="compact-separator">-</span><span>${start}–${end} · ${(c.learnerIds||[]).filter(id=>isActiveLearner(state.learners.find(l=>String(l.id)===String(id)))).length} learners · ${type}</span></div><div class="compact-register-action">${action}</div></div>`}).join('')}else todayEl.innerHTML='<div class="empty">No registers scheduled for today.</div>';
if(upcomingEl){let todayStart=dayStart(todayDate);let ranked=state.classes.map(c=>{if(c.recurring===false){let target=dayStart(c.oneOffDate);let d=Math.round((target-todayStart)/86400000);return d>0?{c,d,date:target}:null}let d=(Number(c.weekday)-day+7)%7;d=d===0?7:d;let date=new Date(todayStart);date.setDate(date.getDate()+d);if(c.recurringStart&&date<dayStart(c.recurringStart)){date=dayStart(c.recurringStart);while(date.getDay()!==Number(c.weekday))date.setDate(date.getDate()+1);d=Math.round((date-todayStart)/86400000)}if(c.recurringEnd&&date>dayStart(c.recurringEnd))return null;return{c,d,date}}).filter(Boolean).sort((a,b)=>a.d-b.d||timeMin(classStart(a.c))-timeMin(classStart(b.c)));let next=ranked[0];if(next){let sessions=next.c.periods.filter(p=>p.type==='session');let end=sessions.length?sessions[sessions.length-1].end:'—';let label=next.c.recurring===false?`One-off · ${next.date.toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'short'})}`:`${weekdayName(next.c.weekday)} ${next.date.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}`;upcomingEl.innerHTML=`<div class="compact-register-row"><div class="compact-register-line"><span class="compact-register-name">${esc(next.c.name)}</span><span class="compact-separator">-</span><span>${label} · ${classStart(next.c)}–${end}</span></div><div class="compact-register-action"><button class="btn small dark" onclick="openClass('${next.c.id}');openRegisterSection('manage')">Edit</button></div></div>`}else upcomingEl.innerHTML='<div class="empty">No upcoming registers.</div>'}
}
function openRegisterSection(section){$('registerSummaryView').style.display='none';$('manageRegistersView').style.display=section==='manage'?'block':'none';$('registerLogsView').style.display=section==='logs'?'block':'none';window.scrollTo({top:0,behavior:'instant'})}
function closeRegisterSection(){$('registerSummaryView').style.display='block';$('manageRegistersView').style.display='none';$('registerLogsView').style.display='none';window.scrollTo({top:0,behavior:'instant'})}
function openStart(){if(state.live)return alert('A register is already active.');if(!state.classes.length)return alert('Create a class first.');$('startClass').innerHTML=state.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('startDate').value=dateISO(now());openM('startModal')}
function startRegister(){let c=state.classes.find(x=>x.id===$('startClass').value);if(!c)return;let regDate=$('startDate').value;if(isClassOnHoliday(c.id,regDate))return alert(`${c.name} is on holiday on ${dateFmt(regDate)} (${classHolidayReason(c.id,regDate)}). No register is required.`);let learnerIds=(c.learnerIds||[]).filter(id=>isActiveLearner(state.learners.find(l=>String(l.id)===String(id)))),present={},events={};learnerIds.forEach(id=>{present[id]=false;events[id]=[]});state.live={id:uid('reg'),classId:c.id,className:c.name,date:regDate,periods:JSON.parse(JSON.stringify(c.periods)),learnerIds,present,events,startedAt:now().toISOString(),completed:false};closeM('startModal');save();document.querySelector('[data-page="registers"]').click();window.scrollTo({top:0,behavior:'instant'});processClock()}
function currentPeriod(){if(!state.live)return null;let m=nowMinutes();return state.live.periods.find(p=>m>=timeMin(p.start)&&m<timeMin(p.end))||null}
function nextPeriod(){if(!state.live)return null;let m=nowMinutes();return state.live.periods.find(p=>timeMin(p.start)>m)||null}
function liveSessions(live=state.live){return live?live.periods.filter(p=>p.type==='session'):[]}
function learnerEvents(id,live=state.live){if(!live)return[];if(!live.events)live.events={};if(!Array.isArray(live.events[id]))live.events[id]=[];return live.events[id]}
function presenceAt(id,minute,live=state.live){let present=false;for(let e of learnerEvents(id,live).slice().sort((a,b)=>a.minute-b.minute)){if(e.minute<=minute)present=!!e.present;else break}return present}
function sessionSegmentsFromEvents(id,p,live=state.live,limitMinute=null){let start=timeMin(p.start),end=timeMin(p.end),limit=limitMinute==null?end:Math.min(end,limitMinute);if(limit<=start)return[];let events=learnerEvents(id,live).slice().sort((a,b)=>a.minute-b.minute);let firstSession=liveSessions(live)[0]?.id===p.id;let present=presenceAt(id,start,live),segments=[],open=null;if(present){let early=firstSession?events.filter(e=>e.present&&e.minute<=start).slice(-1)[0]:null;open={inMinute:early?early.minute:start,inTime:early?.time||`${live.date}T${p.start}:00`,outMinute:null,outTime:null}}
for(let e of events){if(e.minute<start||e.minute>=limit)continue;if(e.present&&!present){open={inMinute:e.minute,inTime:e.time,outMinute:null,outTime:null};present=true}else if(!e.present&&present){if(open){open.outMinute=e.minute;open.outTime=e.time;segments.push(open);open=null}present=false}}
if(open){open.outMinute=limit;open.outTime=null;segments.push(open)}return segments}
function learnerLiveMinutes(id,live=state.live){if(!live||isLearnerOnHoliday(id,live.date))return 0;let m=nowMinutes(),total=0;for(let p of liveSessions(live)){let start=timeMin(p.start);if(m<=start&&p.id!==liveSessions(live)[0]?.id)continue;let limit=Math.min(m,timeMin(p.end));for(let seg of sessionSegmentsFromEvents(id,p,live,limit))total+=Math.max(0,(seg.outMinute??limit)-seg.inMinute)}return Math.round(total)}
function tickLearner(id){if(!state.live||isLearnerOnHoliday(id,state.live.date))return;let minute=nowMinutes(),sessions=liveSessions(),first=sessions[0],last=sessions[sessions.length-1];if(!first||minute>=timeMin(last.end))return;let current=!!state.live.present?.[id];if(!state.live.present)state.live.present={};state.live.present[id]=!current;learnerEvents(id).push({minute,time:now().toISOString(),present:!current});save()}
function plannedMinutes(live=state.live){return live.periods.filter(p=>p.type==='session').reduce((s,p)=>s+timeMin(p.end)-timeMin(p.start),0)}
function buildResults(live){let sessions=liveSessions(live);return live.learnerIds.map(id=>{let holiday=isLearnerOnHoliday(id,live.date,live.classId),credited=0,attendedSessions=0;let details=sessions.map(p=>{let dur=timeMin(p.end)-timeMin(p.start);if(holiday)return{periodId:p.id,label:p.label,status:'On holiday',credited:0,net:0,segments:[]};let segments=sessionSegmentsFromEvents(id,p,live,timeMin(p.end));let sessionCredited=Math.round(segments.reduce((n,x)=>n+Math.max(0,(x.outMinute??timeMin(p.end))-x.inMinute),0));if(sessionCredited>0)attendedSessions++;credited+=sessionCredited;return{periodId:p.id,label:p.label,status:sessionCredited>0?'Attended':'Absent',credited:sessionCredited,net:sessionCredited-dur,segments}});return{learnerId:id,holiday,creditedMinutes:credited,netMinutes:holiday?0:credited-plannedMinutes(live),attendedSessions,totalSessions:holiday?0:sessions.length,details}})}
function completeDay(auto=false){if(!state.live)return;let live=state.live;let log={...live,plannedMinutes:plannedMinutes(live),results:buildResults(live),completedAt:now().toISOString(),autoCompleted:auto};delete log.events;delete log.present;state.logs.unshift(log);state.live=null;state.demoTime=null;save();document.querySelector('[data-page="registers"]')?.click()}
function discardLive(){if(confirm('Discard this live register?')){state.live=null;state.demoTime=null;save()}}
function setDemoTime(){let v=$('demoClockInput')?.value;if(!v)return;let date=state.live?.date||dateISO();state.demoTime=new Date(`${date}T${v}:00`).toISOString();save();processClock()}
function useRealTime(){state.demoTime=null;save();processClock()}
function advanceDemo(minutes){let base=now();state.demoTime=new Date(base.getTime()+minutes*60000).toISOString();save();processClock()}
function renderLive(){
let el=$('liveRegister'),panel=$('liveRegisterPanel'),dashboard=$('registerDashboard');
if(!state.live){if(panel)panel.style.display='none';if(dashboard)dashboard.style.display='block';el.innerHTML='';return}
if(panel)panel.style.display='block';if(dashboard)dashboard.style.display='none';
let live=state.live,p=currentPeriod(),m=nowMinutes(),sessions=liveSessions(),first=sessions[0],last=sessions[sessions.length-1];
let active=p;
if(!active&&m<timeMin(first.start)) active=first;
if(!active&&m>=timeMin(last.end)) active=last;
let startMin=timeMin(active.start),endMin=timeMin(active.end),duration=Math.max(1,endMin-startMin);
let progress=m<=startMin?0:m>=endMin?100:Math.max(0,Math.min(100,((m-startMin)/duration)*100));
let label=m<timeMin(first.start)?`${first.label} starts at ${first.start}`:m>=timeMin(last.end)?'Teaching day complete':active.label;
let timeLabel=m>=timeMin(last.end)?`${last.end}`:`${active.start}–${active.end}`;
let progressClass=m>=timeMin(last.end)?'complete-progress':active.type==='break'?'break-progress':'';
el.innerHTML=`<div class="live-register-title"><h2>${esc(live.className)}</h2></div><div class="period-progress-wrap ${progressClass}"><div class="period-progress-head"><span>${esc(label)}</span><span>${esc(timeLabel)}</span></div><div class="period-progress-track"><div class="period-progress-fill" style="width:${progress.toFixed(2)}%"></div></div></div><div class="register-list" style="margin-top:12px">${live.learnerIds.map(id=>{let holiday=isLearnerOnHoliday(id,live.date,live.classId),checked=!!live.present?.[id],mins=learnerLiveMinutes(id);return `<div class="tick-card ${checked?'checked':''} ${holiday?'holiday-card':''}" ${holiday?'':`onclick="tickLearner('${id}')"`}><div class="tick-name">${esc(learnerName(id))}</div><div class="tick-attendance">${holiday?'<span class="holiday-badge">On holiday</span>':`<span>${minText(mins)}</span>`}</div><div class="tick-box">${holiday?'—':checked?'✓':''}</div></div>`}).join('')}</div>`
}
function liveScheduledEnd(live=state.live){
if(!live)return null;
let sessions=liveSessions(live),last=sessions[sessions.length-1];
if(!last||!live.date)return null;
return new Date(`${live.date}T${last.end}:00`)
}
function recoverOverdueRegister(){
if(!state.live)return false;
let scheduledEnd=liveScheduledEnd(state.live);
if(!scheduledEnd||now().getTime()<scheduledEnd.getTime())return false;
completeDay(true);
return true
}
function processClock(){
if(!state.live)return renderLive();
if(recoverOverdueRegister())return;
renderLive()
}
